- name: Install pip for Ubuntu
  apt:
    name: python3-pip
    install_recommends: yes
    force_apt_get: yes
    state: latest
  become: true

#- name: pip self-update
#  pip:
#    name: pip
#    state: latest
